### ISSUE TITLE
can't add custom attributes using Paris

### ISSUE THREAD

**Issue by ftabashir** [airbnb/paris#116]
I have some custom attributes in `attrs.xml`
```
</resources>
    <declare-styleable name="CustomButton">
        <attr name="textColor" format="color"/>
    </declare-styleable>
</resources>
```
and added `@Styleable("CustomButton")` to the `CustomButton` class.

But when I try `@Attr(R.styleable.CustomButton_textColor)`  compiler tells me:

> An annotation argument must be a compile-time constant

I also tried to use `R2` class but there is no generated `CustomButton_textColor` in `R2`.

Here is my dependencies:
```
implementation 'com.airbnb.android:paris:1.3.0'
kapt 'com.airbnb.android:paris-processor:1.3.0'
```

**Comment by rbro112** [comment]
I might be a bit too late here, but just ran into this same issue. I finally figured out that I needed to use Jake Wharton's butterknife plugin to properly generate the `R2` file (`R` doesn't seem to work still).

At my project level `build.gradle`, I just added `classpath 'com.jakewharton:butterknife-gradle-plugin:10.1.0'` to `dependencies. That should allow you to use R2 and `@Attr` annotations should work properly!

**Comment by ngsilverman** [comment]
@ftabashir this error suggest that you're doing this in a library project (rather than an application project)? Can you confirm? If so using `R2` is the right approach, if it's not being generated it's probably that you didn't setup the Butterknife Gradle plugin, as pointed out by @rbro112. You can find setup instructions here: https://github.com/airbnb/paris/wiki/Library-Modules#r-values-and-annotations
