### ISSUE TITLE
Is it possible to apply multiple styles from xml? 

### ISSUE THREAD

**Issue by AlexMisiulia** [airbnb/paris#38]
It will be really cool to use this as `app:styles="@Style/Style1, @Style/Style2"`.
Do you think it is possible (even if need to create wrapper for each view)?

**Comment by ngsilverman** [comment]
Hey @AlexMisiulia ! It's an interesting idea. Could you provide more context as to why you'd like to be able to do this from XML instead of doing it programmatically with a style builder?

For example:
```java
Paris.styleBuilder(view)
        .add(R.style.Style1)
        .add(R.style.Style2)
        .apply();
```

----

Using this syntax `app:styles="@style/Style1, @style/Style2"` means we could get the value as a string `"@style/Style1, @style/Style2"`. From there we could conceivably reflectively look up `R.style.Style1` and `R.style.Style2` and apply them.

However this would only work for custom views that call `Paris.style(this).apply(attributeSet)` as they're initialized. Other views (`TextView`, `EditText`, `LinearLayout`, any Android view) naturally don't go through Paris to read and set their attributes when they're inflated from XML. Although they could be made to if we provided our own [LayoutInflater.Factory2](https://developer.android.com/reference/android/view/LayoutInflater.Factory2.html).

----

Another option that would only apply to custom views could be to refer to linked styles from XML. The style would be defined like so:
```java
class MyView ... {
    @Style
    static void greenStyle(MyViewStyleApplier.StyleBuilder builder) {
        builder.add(R.style.Style1)
                .add(R.style.Style2);
    }
}
```
And applied:
```xml
<MyView
        ...
        app:parisStyle="green"
        />
```

Android views could be subclassed to allow them to be restyled in this way:
```java
class MyTextView extends TextView {
    // constructors and nothing else

    @Style
    static void multipleStyle(MyViewStyleApplier.StyleBuilder builder) {
        builder.add(R.style.Style1)
                .add(R.style.Style2);
    }
}
```

One downside is renaming styles with one refactoring action wouldn't work. 🤔

**Comment by AlexMisiulia** [comment]
@ngsilverman Thank you for response, sorry for multiple issues.
I think that it is the best way to work with styles from `xml` (inspired by `CSS` powerful styles).

I like your solution, will try to use one of them.

Nice lib, thanks for develop!
