### ISSUE TITLE
What about proguard? 

### ISSUE THREAD

**Issue by Kolyall** [airbnb/paris#50]
What to add to proguard if `minifyEnabled true`?

**Comment by ngsilverman** [comment]
@Kolyall have you tried it? Everything should work just fine, Paris doesn't use reflection.

**Comment by ntanduc2288** [comment]
I got the following error when enabling 'minifyEnabled true'
` Caused by: java.lang.ClassNotFoundException: Didn't find class "android.widget.TextViewStyleApplier" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.ubermind.rei-PRsNhRiIxxt-crrjXZIPZg==/base.apk", zip file "/data/app/com.ubermind.rei-PRsNhRiIxxt-crrjXZIPZg==/split_lib_directories_apk.apk"],nativeLibraryDirectories=[/data/app/com.ubermind.rei-PRsNhRiIxxt-crrjXZIPZg==/lib/arm64, /data/app/com.ubermind.rei-PRsNhRiIxxt-crrjXZIPZg==/base.apk!/lib/arm64-v8a, /data/app/com.ubermind.rei-PRsNhRiIxxt-crrjXZIPZg==/split_lib_directories_apk.apk!/lib/arm64-v8a, /system/lib64]]`

**Comment by ngsilverman** [comment]
@ntanduc2288 can you open a new issue and post the full stacktrace? Thanks.
