### ISSUE TITLE
Applying Paris to Epoxy-enabled custom view clears default layout styling

### ISSUE THREAD

**Issue by plnice** [airbnb/paris#53]
Paris 1.0.0
Epoxy 2.12.0
Android library module (though it shouldn't make a difference)

I'm using Paris to take advantage of `@Attr` annotation. Following example should produce view with red background (which is specified in the default layout). However, it looks like the styling is cleared due to some Paris magic.

```kotlin
Component.kt
------------
@ModelView(defaultLayout = R2.layout.default_component_layout)
@Styleable("Component")
class Component @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0) :
        ConstraintLayout(context, attrs, defStyleAttr) {

    init {
        inflate(R.layout.component_inner_layout)
        Paris.style(this).apply(attrs)
    }

    @Attr(R2.styleable.Component_title)
    @TextProp
    fun setTitle(text: CharSequence) {
        title.text = text // kotlinx.android.syntethic
    }

}
```
```xml
default_component_layout.xml
----------------------------
<my.package.Component xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="56dp"
    android:background="@color/red"/>
```
```xml
component_inner_layout.xml
-----------------------
<merge xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:parentTag="android.support.constraint.ConstraintLayout">

    <TextView
        android:id="@+id/title"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent"
        tools:text="Test" />

</merge>
```
```xml
attrs.xml
---------
<declare-styleable name="Component">
    <attr name="title" format="string" />
</declare-styleable>

```

Removing Paris from the view makes the default layout styling work correctly:

```kotlin
Component.kt
------------
@ModelView(defaultLayout = R2.layout.default_component_layout)
// @Styleable("Component")
class Component @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0) :
        ConstraintLayout(context, attrs, defStyleAttr) {

    init {
        inflate(R.layout.component_inner_layout)
        // Paris.style(this).apply(attrs)
    }

    // @Attr(R2.styleable.Component_title)
    @TextProp
    fun setTitle(text: CharSequence) {
        title.text = text // kotlinx.android.syntethic
    }

}
```

**Comment by ngsilverman** [comment]
@plnice thank you for the thorough report! I think I know what's going on. By adding `@Styleable` to a `@ModelView` you've enabled [Epoxy's Paris integration](https://github.com/airbnb/epoxy/wiki/Paris-Integration-(Dynamic-Styling)):

> Notice that no view holder or layout information needs to be provided to the @ModelView annotation. This is because Epoxy creates the view programmatically and styles it completely with Paris. By default the view's default style is used, per Paris's default rules.

What's happening in this case is `defaultLayout = R2.layout.default_component_layout` is completely ignored. Rather than inflating `default_component_layout.xml` to create a new `Component`, Epoxy creates it programmatically and applies the default Paris style (which will be empty by default).

I would suggest that you leverage this by deleting `default_component_layout.xml` and trying this:
```kotlin
Component.kt
------------
@Styleable("Component")
@ModelView
class Component @JvmOverloads constructor(
        context: Context, attrs: AttributeSet? = null, defStyleAttr: Int = 0) :
        ConstraintLayout(context, attrs, defStyleAttr) {

    init {
        inflate(R.layout.component_inner_layout)
        Paris.style(this).apply(attrs)
    }

    @Attr(R2.styleable.Component_title)
    @TextProp
    fun setTitle(text: CharSequence) {
        title.text = text // kotlinx.android.syntethic
    }

    companion object {
        @JvmStatic
        @Style
        fun defaultStyle(builder: ComponentStyleApplier.StyleBuilder) {
            builder.layoutWidth(LayoutParams.MATCH_PARENT)
                .layoutHeightDp(56)
                .backgroundRes(R.color.red)
        }
    }

}
```

**Comment by plnice** [comment]
Thanks for the reply. I've tried using the solution with `defaultStyle` static method but it fails with:
```
com.airbnb.paris.processor.framework.errors.ProcessorException: defaultStyle: Fields and methods annotated with @Style must be static and can't be private or protected
```
even though there's `@JvmStatic` annotation specified.

Also I've tried specifying default XML style:
```kotlin
@Style
const val DEFAULT_STYLE = R2.style.Component
```
which passes the build, but the style is not applied.

My third attempt was to specify style when adding model to Epoxy controller:
```kotlin
    override fun buildModels(data: Unit) {
        component {
            id(0)
            title(R.string.app_name)
            styleBuilder { builder -> builder.layoutWidth(MATCH_PARENT).layoutHeightDp(56).backgroundRes(R.color.red) }
        }
    }
```
but it caused crash at runtime with:
```
    java.lang.IllegalStateException: ComponentModel_ model at position 0 has an invalid style:
    
    The Component style "EmptyStyle" is missing the following attributes:
    ✕ layout_height
    ✕ layout_width
    ✕ background
    It must declare the same attributes as the following styles:
    a_programmatic_StyleBuilder
```
when there was no `DEFAULT_STYLE` specified and
```
    android.content.res.Resources$NotFoundException: Unable to find resource ID #0x7f1600ae
        at android.content.res.ResourcesImpl.getResourceEntryName(ResourcesImpl.java:279)
        at android.content.res.Resources.getResourceEntryName(Resources.java:2002)
        at com.airbnb.paris.styles.ResourceStyle.name(ResourceStyle.kt:18)
        at com.airbnb.paris.StyleApplierUtils$Companion.getMissingStyleAttributesError(StyleApplierUtils.kt:86)
        at com.airbnb.paris.StyleApplierUtils$Companion.assertSameAttributes(StyleApplierUtils.kt:73)
        at com.github.plnice.uilibrary.ComponentModel_$1.run(ComponentModel_.java:86)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```
when there's `DEFAULT_STYLE` specified (#0x7f1600ae is the default style resource id).

I've created a sample project that reproduces the issues: https://github.com/plnice/paris-playground. Thanks for your assistance.

**Comment by ngsilverman** [comment]
@plnice my bad! Paris version `1.0.0` was only ever tested with Java, I assumed that `@JvmStatic` would work but under the hood Kotlin ends up creating two methods, one of which isn't static which causes the error.

----

```kotlin
@Style
const val DEFAULT_STYLE = R2.style.Component
```

This doesn't work as expected because it uses `R2` rather than `R`. Unfortunately after fixing that it runs into an issue similar to the one using a function.

----

Using the Epoxy model style builder also doesn't work because it enforces that the same attributes be declared for all styles used on a given view type for recycling purposes. See [paris/wiki/View-Recycling](https://github.com/airbnb/paris/wiki/View-Recycling) for more info.

----

In a nutshell, it all boils down to Kotlin not being supported. Luckily that's what I've been working on for the next version which is pretty much ready to go. Changing the Paris version to `1.1.0-SNAPSHOT` in your playground made this work:

```kotlin
class Component ... {

    ...

    companion object {

        @Style
        val DEFAULT_STYLE = R.style.Component
    }
}
```

Alternatively, if you would prefer to declare the style programmatically, you can leverage this new Kotlin-only syntax (this should also be placed in the `companion object`):

```kotlin
@Style
val DEFAULT_STYLE = componentStyle {
    layoutWidth(LayoutParams.MATCH_PARENT)
    layoutHeightDp(56)
    backgroundRes(R.color.red)
}
```

Make sure to add the snapshot repositories to your projects in `build.gradle`:

```diff
 allprojects {
     repositories {
         google()
         jcenter()
+        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
     }
 }
```

**Comment by plnice** [comment]
1.0.0-SNAPSHOT works fine - thanks a lot!
