### ISSUE TITLE
Where is layout_weight ?

### ISSUE THREAD

**Issue by rene-dohan** [airbnb/paris#90]
I was trying to apply some simple layout, but could it be that layout_weight is not supported ?
I also did not found it in docs...
Thanks, until now it was like wow...

**Comment by ngsilverman** [comment]
Hi @rene-dohan, `layout_weight` is not currently supported, however adding support for new attributes is possible and fairly straightforward. If you're interested in contributing, you can take a look at https://github.com/airbnb/paris/blob/master/paris/src/main/java/com/airbnb/paris/proxies/ViewProxy.kt to see how other attributes are supported. Otherwise I'll take this as a request and will add support for `layout_weight` when I'm able to!
